config/routes.rb
Rails.application.routes.draw do

  get 'posts/index'
  post 'posts/upload_post', as: 'upload_post'
  get 'p/:id', to: 'posts#view', as: :post
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'lp/:id', to: 'likes#like_post', as: 'like'
  get 'up/:id', to: 'likes#unlike_post', as: 'unlike'

  post 'p/:id', to: 'posts#post_comment', as: 'post_comment'

  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like_post
    @user = current_user
    @post = Post.find(params[:id])
    Like.create(user_id: @user.id, post_id: @post.id)
    redirect_to post_path(@post.id)
  end

  def unlike_post
    @user = current_user
    @post = Post.find(params[:id])
    @like = Like.where(user_id: @user.id, post_id: @post.id).first
    @like.destroy
    redirect_to post_path(@post.id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = current_user
    @post = Post.new
  end

  def upload_post
    @user = current_user
    @post = @user.posts.create(post_params)
    redirect_to post_path(@post.id)
  end

  def view
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def likes(user, post)
    array = []
    @likes = post.likes
    @likes.each do |like|
      array.push(like.user_id)
    end
    return array.include?(user.id)
  end

  def count_likes(post)
    number = post.likes.count
    if number == 0
      return nil
    elsif number == 1
      return "1 like"
    else
      return number.to_s + " likes"
    end
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSPagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in?  %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<section class="comment-box">

<%= form_for @comment, url: post_comment_path(@post.id), html: {class: "comment-form"} do |f| %>
<%= f.text_field :text, placeholder: "Add a comment...", class: "comment-text" %>
<%= f.hidden_field :user_id, value: @user.id %>
<%= f.hidden_field :post_id, value: @post.id %>

<% end %>


</section>

app/views/posts/index.html.erb
<%= form_for @post, url: upload_post_path do |f| %>

<%= f.file_field :image %>

<p><%= f.submit "Submit" %></p>
<% end %>

app/views/posts/view.html.erb
<%= image_tag @post.image %>

<%= link_to "Like", like_path(@post.id) %>
<%= link_to "Unlike", unlike_path(@post.id) %>

<%= count_likes(@post) %>


<div class="commentsForm">
  <%= render 'posts/comment' %>
</div>